language: java
os: linux
sudo: false

jdk: 
# - oraclejdk9
# - oraclejdk8
  - openjdk14


cache:
  directories:
  - $HOME/.m2


notifications:
  email:
    on_success: never


# will be executed before maven is called
before_install:
# no matter what format we have locally, travis should always generate the zip file
- sed -i -e 's/<format>dir<\/format>/<format>zip<\/format>/g' src/main/resources/assembly.xml

# Test
- cp .travis.settings.xml $HOME/.m2/settings.xml

# make sure we have a clean target folder
- rm -rf target/*


install: mvn -e install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml


before_deploy:
- export DEPLOY_FILE=$(ls target/aptasuite*.zip)


deploy:
  provider: releases
  api_key:
    #secure: ZVPKbJvQvQWzV3oQDgsm8Csyamd6uKbDNYY2JEXDz+VHRQ0XVTmuJQi4FsvU+7nJoTIDG7hgxPKGZidBgi7rfyWB6fXj0LgdXPyAps4HDc7G0tWQgZDLpmdHCADgwduK3eqVDLliM6W/MiQfCyjrNVZ7HYkeowjDs3UByWtqH1M16tafP7j0ZHZO35/AUi75zocxZz+N9SrPnR6Qap3eO4SnEcLu++JFRLB5NwdgREPtrzpSaoOIIlJ/ZjCcqBZLfy8RPgRJrXE0HYigQ9nlvekNBwG+RdBkz0tzgnplPGYNq0L//HoeIFMIShCWpXAnpsh75QW5Vp92m4gzp7iyNXtpfpR0D+M/lCxSQi/rE3RtJOrBgkQzf4xgyH+TmF94dhjMJpLMKUNVP8NPI74zQjSDGi/39G42ulopT73CBXMB5r2FpoYsUkcoXlkCrba5lQ1asOp2AyKdQ17dccalbVGf/TvfMaWv/ZywG8XdRqT3nF4gTIqFVrWO3zh9kjC+woa7kHvO3acWDxyOjKAHSqW1o6Zq550NqMSTMxldX78JbX03Q4IVYyalTIBo1Cz+4resIOLE9tojCcjY8KbVFFhh3O9V6KfW2zJteFazOk5O2atuV0SGbYMtO3WhLPyPwzAySVHfzU3yUtFZBaAgjPLslTT3zj2TIeArnZ6QCZE=
    secure: u8SF6exq0fiQ4eTjiX9cJB4W9+MDjMv8Zqtfrc9aNkCZZwyJ7pIMDtPB2uWOiFNLts35kKwGTt/w9kCvUihlhIaQWnpJligVyeW7p1cfUUzwPxs0QuRKQTwwdXwTDK07s8KeZM9qIVVRA8EVC3JWBgKEdjGFlDQs8PE26tqhmSWukf/8UpBghVpy3kWEexmyfKH07TTzUG1K8I7zittl/ug7lied8eeh0ngmeh7TZdwZQyibZ8ttFD7UUp5sXpPvEg915/9UfE+Bl3luJuukBQ5f32Ox/5phOShbF6bY+/FgGMdG0e3W3HXXFdbRzlsU7sA1czEfolL/GceI642Wu7OPqiFW2qo0eKxnOvZWhp6cR2xEVWYG5PcFZKYeCKG5PDBiuwb9QLeTZ+6MT9BSb/+1nJYhert6Bb5smI9IzqOzmCF3OQt8MhOQZcgbTzfkGEftADPOGwkwFy9LhpTbHNiksE0++wnlAw8lyFNN50mQNIdQ0GV+k2qzk40EK5TkthGGf22hnEdzvxz36i4FErOm6BM04zG6wPWNuYuZ4YJkQl4LXZuLabSPDmADhIYoi5UVnFwwbWafktDhmz8bPRNTVElvZtozG1JA8dbUYsqEkbS/ZbIJjNA9Yu2/7wMEL698r8OzEy4gIJb4BU3UjRPrsfybDCB4c7l6pgmXSOc=
  skip_cleanup: true
  file: "${DEPLOY_FILE}"
  overwrite: true
  edge: true 
  on:
    repo: drivenbyentropy/aptasuite
    tags: true
    jdk: openjdk14