language: java

matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk9
      
    - os: linux
      sudo: false
      jdk: oraclejdk8

#    - os: osx
#      sudo: false
#      jdk: oraclejdk9
#      
#    - os: osx
#      sudo: false
#      jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    on_success: never

# will be executed before maven is called
before_install: 
 # no matter what format we have locally, travis should always generate the zip file
 - sed -i -e 's/<format>dir<\/format>/<format>zip<\/format>/g' src/main/resources/assembly.xml
 
 # make sure we have a clean target folder
 - rm -rf target/*
 - ls -lah target/
 
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml